/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 10 01:28:31 GMT 2024
 */

package org.exolab.jms.tools.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTree;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.exolab.jms.tools.admin.AdminInfo;
import org.exolab.jms.tools.admin.OpenJMSConsumer;
import org.exolab.jms.tools.admin.OpenJMSObject;
import org.exolab.jms.tools.admin.OpenJMSQueue;
import org.exolab.jms.tools.admin.OpenJMSTopic;
import org.exolab.jms.tools.admin.OpenJMSTopicFolder;
import org.exolab.jms.tools.admin.OpenJMSUser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AdminInfo_ESTest extends AdminInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = OpenJMSObject._tree;
      OpenJMSTopicFolder openJMSTopicFolder0 = new OpenJMSTopicFolder((JTree) null);
      // Undeclared exception!
      try { 
        adminInfo0.getTreeCellRendererComponent(jTree0, openJMSTopicFolder0, false, true, false, 0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = new JTree();
      OpenJMSQueue openJMSQueue0 = new OpenJMSQueue("", jTree0);
      Component component0 = adminInfo0.getTreeCellRendererComponent(jTree0, openJMSQueue0, false, false, false, 0, false);
      component0.setIgnoreRepaint(true);
      Component component1 = adminInfo0.getTreeCellRendererComponent(jTree0, component0, false, false, true, 1, false);
      assertTrue(component1.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = new JTree();
      OpenJMSQueue openJMSQueue0 = new OpenJMSQueue("", jTree0);
      Component component0 = adminInfo0.getTreeCellRendererComponent(jTree0, openJMSQueue0, false, false, true, 0, false);
      component0.setFocusTraversalKeysEnabled(false);
      JPanel jPanel0 = (JPanel)adminInfo0.getTreeCellRendererComponent(jTree0, component0, false, false, true, 1, false);
      assertFalse(jPanel0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      OpenJMSTopicFolder openJMSTopicFolder0 = new OpenJMSTopicFolder((JTree) null);
      JTree jTree0 = new JTree(openJMSTopicFolder0);
      JPanel jPanel0 = (JPanel)adminInfo0.getTreeCellRendererComponent(jTree0, openJMSTopicFolder0, true, true, true, 0, true);
      assertFalse(jPanel0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = new JTree();
      OpenJMSUser openJMSUser0 = new OpenJMSUser("PDC0{.Ec}", jTree0);
      JPanel jPanel0 = (JPanel)adminInfo0.getTreeCellRendererComponent(jTree0, openJMSUser0, true, true, true, 5, true);
      assertFalse(jPanel0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = new JTree();
      OpenJMSConsumer openJMSConsumer0 = new OpenJMSConsumer("", jTree0);
      JPanel jPanel0 = (JPanel)adminInfo0.getTreeCellRendererComponent(jTree0, openJMSConsumer0, true, true, false, 3301, false);
      assertFalse(jPanel0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AdminInfo adminInfo0 = new AdminInfo();
      JTree jTree0 = new JTree();
      OpenJMSTopic openJMSTopic0 = new OpenJMSTopic("", jTree0);
      JPanel jPanel0 = (JPanel)adminInfo0.getTreeCellRendererComponent(jTree0, openJMSTopic0, false, false, false, 1, true);
      assertFalse(jPanel0.isFocusTraversalPolicySet());
  }
}
