/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Mar 09 23:38:58 GMT 2024
 */

package com.liferay.portal.security.pacl.checker;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class PortalHookChecker_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.liferay.portal.security.pacl.checker.PortalHookChecker"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.country", "CL"); 
    java.lang.System.setProperty("user.dir", "/Users/njimenez/Documents/Magister/100Clases/Test1/projects og/108_liferay"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/zt/9k543zcs7kb243_mzg2jl49w0000gn/T/"); 
    java.lang.System.setProperty("user.name", "njimenez"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PortalHookChecker_ESTest_scaffolding.class.getClassLoader() ,
      "com.liferay.portal.kernel.security.pacl.permission.PortalHookPermission",
      "org.bouncycastle.asn1.ntt.NTTObjectIdentifiers",
      "org.bouncycastle.asn1.kisa.KISAObjectIdentifiers",
      "com.liferay.portal.kernel.security.pacl.permission.PortalRuntimePermission",
      "org.bouncycastle.jce.provider.symmetric.Grain128Mappings",
      "org.bouncycastle.asn1.DERObject",
      "org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers",
      "com.liferay.portal.security.pacl.checker.PortalHookChecker",
      "com.liferay.portal.security.pacl.BasePACLPolicy",
      "org.bouncycastle.asn1.DEREncodable",
      "org.bouncycastle.jce.provider.symmetric.Grainv1Mappings",
      "org.bouncycastle.jce.provider.symmetric.NoekeonMappings",
      "org.bouncycastle.jce.provider.symmetric.SEEDMappings",
      "com.liferay.portal.kernel.log.Log",
      "com.liferay.portal.kernel.log.LogFactory",
      "com.liferay.portal.kernel.log.Jdk14LogFactoryImpl",
      "org.bouncycastle.asn1.oiw.OIWObjectIdentifiers",
      "org.bouncycastle.asn1.cryptopro.CryptoProObjectIdentifiers",
      "org.bouncycastle.jce.provider.symmetric.CAST5Mappings",
      "org.bouncycastle.asn1.iana.IANAObjectIdentifiers",
      "com.liferay.portal.security.pacl.ActivePACLPolicy",
      "org.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers",
      "com.liferay.portal.kernel.log.LogWrapper",
      "com.liferay.portal.kernel.util.SortedProperties",
      "org.bouncycastle.asn1.nist.NISTObjectIdentifiers",
      "org.bouncycastle.asn1.ASN1Object",
      "org.bouncycastle.asn1.DERObjectIdentifier",
      "org.bouncycastle.asn1.ASN1Encodable",
      "org.bouncycastle.jce.provider.symmetric.AESMappings",
      "com.liferay.portal.kernel.log.LogFactoryUtil",
      "com.liferay.portal.security.pacl.PACLPolicy",
      "com.liferay.portal.security.pacl.checker.BaseChecker",
      "com.liferay.portal.security.pacl.InactivePACLPolicy",
      "com.liferay.portal.kernel.log.Jdk14LogImpl",
      "org.bouncycastle.jce.provider.BouncyCastleProvider",
      "org.bouncycastle.jce.provider.asymmetric.ECMappings",
      "com.liferay.portal.kernel.util.PropsUtil",
      "org.bouncycastle.jce.interfaces.ConfigurableProvider",
      "org.bouncycastle.asn1.x9.X9ObjectIdentifiers",
      "org.bouncycastle.asn1.eac.EACObjectIdentifiers",
      "com.liferay.portal.security.pacl.checker.Checker",
      "org.bouncycastle.jce.provider.BouncyCastleProvider$1",
      "org.bouncycastle.jce.provider.symmetric.CamelliaMappings",
      "org.bouncycastle.asn1.bc.BCObjectIdentifiers",
      "com.liferay.portal.kernel.util.Props",
      "com.liferay.portal.kernel.security.pacl.PACLConstants",
      "org.bouncycastle.asn1.DERTags"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PortalHookChecker_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.liferay.portal.kernel.log.Jdk14LogFactoryImpl",
      "com.liferay.portal.kernel.log.LogFactoryUtil",
      "com.liferay.portal.kernel.log.LogWrapper",
      "com.liferay.portal.kernel.log.Jdk14LogImpl",
      "com.liferay.portal.security.pacl.checker.BaseChecker",
      "com.liferay.portal.security.pacl.checker.PortalHookChecker",
      "org.springframework.transaction.annotation.Propagation",
      "org.springframework.transaction.annotation.Isolation",
      "com.liferay.portal.kernel.security.pacl.permission.PortalRuntimePermission",
      "org.bouncycastle.asn1.ASN1Encodable",
      "org.bouncycastle.asn1.x509.X509CertificateStructure",
      "com.liferay.portal.kernel.security.pacl.permission.PortalHookPermission",
      "org.bouncycastle.jce.provider.BouncyCastleProvider",
      "org.bouncycastle.jce.provider.BouncyCastleProvider$1",
      "org.bouncycastle.jce.provider.symmetric.AESMappings",
      "org.bouncycastle.asn1.DERObject",
      "org.bouncycastle.asn1.ASN1Object",
      "org.bouncycastle.asn1.DERObjectIdentifier",
      "org.bouncycastle.asn1.nist.NISTObjectIdentifiers",
      "org.bouncycastle.jce.provider.symmetric.CamelliaMappings",
      "org.bouncycastle.asn1.ntt.NTTObjectIdentifiers",
      "org.bouncycastle.jce.provider.symmetric.CAST5Mappings",
      "org.bouncycastle.jce.provider.symmetric.Grainv1Mappings",
      "org.bouncycastle.jce.provider.symmetric.Grain128Mappings",
      "org.bouncycastle.jce.provider.symmetric.NoekeonMappings",
      "org.bouncycastle.jce.provider.symmetric.SEEDMappings",
      "org.bouncycastle.asn1.kisa.KISAObjectIdentifiers",
      "org.bouncycastle.jce.provider.asymmetric.ECMappings",
      "org.bouncycastle.asn1.x9.X9ObjectIdentifiers",
      "org.bouncycastle.asn1.cryptopro.CryptoProObjectIdentifiers",
      "org.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers",
      "org.bouncycastle.asn1.eac.EACObjectIdentifiers",
      "org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers",
      "org.bouncycastle.asn1.oiw.OIWObjectIdentifiers",
      "org.bouncycastle.asn1.bc.BCObjectIdentifiers",
      "org.bouncycastle.asn1.iana.IANAObjectIdentifiers",
      "com.liferay.portal.security.pacl.BasePACLPolicy",
      "com.liferay.portal.security.pacl.InactivePACLPolicy",
      "com.liferay.portal.kernel.util.PropsUtil",
      "org.bouncycastle.asn1.ASN1TaggedObject",
      "org.bouncycastle.asn1.DERTaggedObject",
      "org.bouncycastle.asn1.BERTaggedObject",
      "org.bouncycastle.asn1.ASN1Sequence",
      "org.bouncycastle.asn1.DERSequence",
      "org.bouncycastle.asn1.BERSequence",
      "com.liferay.portal.security.pacl.ActivePACLPolicy",
      "com.liferay.portal.security.pacl.checker.JNDIChecker",
      "com.liferay.portal.kernel.util.StringUtil",
      "com.liferay.portal.kernel.util.Validator",
      "com.liferay.portal.kernel.util.SetUtil",
      "com.liferay.portal.security.pacl.checker.PortalServiceChecker",
      "com.liferay.portal.security.pacl.checker.SQLChecker",
      "net.sf.jsqlparser.parser.CCJSqlParserManager",
      "org.bouncycastle.asn1.DEREncodableVector",
      "org.bouncycastle.asn1.ASN1EncodableVector",
      "org.bouncycastle.asn1.DERUTF8String",
      "org.jfree.data.xy.XYDatasetTableModel",
      "org.jfree.data.general.AbstractDataset",
      "org.jfree.data.general.AbstractSeriesDataset",
      "org.jfree.data.xy.AbstractXYDataset",
      "org.jfree.data.jdbc.JDBCXYDataset",
      "org.jfree.data.general.DatasetGroup",
      "org.jfree.data.xy.AbstractIntervalXYDataset",
      "org.jfree.data.xy.CategoryTableXYDataset",
      "org.jfree.data.DefaultKeyedValues2D",
      "org.jfree.data.xy.IntervalXYDelegate",
      "org.jfree.data.xy.DefaultTableXYDataset",
      "org.jfree.data.time.TimeTableXYDataset",
      "org.jfree.data.time.TimePeriodAnchor",
      "org.bouncycastle.asn1.ASN1OctetString",
      "org.bouncycastle.asn1.x509.X509ObjectIdentifiers",
      "org.jgroups.util.DefaultThreadFactory",
      "org.jgroups.util.LazyThreadFactory",
      "org.bouncycastle.asn1.DERBoolean",
      "com.liferay.portal.kernel.util.GetterUtil",
      "org.jruby.threading.DaemonThreadFactory",
      "org.geotools.factory.Hints$Key",
      "org.geotools.factory.Hints$ClassKey",
      "org.geotools.factory.Hints$FileKey",
      "org.geotools.factory.Hints$DataSourceKey",
      "org.geotools.factory.Hints$OptionKey",
      "org.geotools.factory.Hints$IntegerKey",
      "org.geotools.factory.Hints$DoubleKey",
      "org.geotools.factory.Hints",
      "org.bouncycastle.asn1.DEROctetString",
      "com.liferay.portal.kernel.util.StringBundler",
      "com.caucho.config.AdminLiteral",
      "org.bouncycastle.asn1.ASN1Null",
      "org.bouncycastle.asn1.DERNull",
      "org.bouncycastle.asn1.BERNull",
      "org.testng.xml.XmlTest",
      "org.testng.xml.XmlSuite$1",
      "org.testng.xml.XmlSuite",
      "org.testng.collections.Lists",
      "org.testng.collections.Maps",
      "org.bouncycastle.asn1.DERConstructedSequence",
      "org.bouncycastle.asn1.BERConstructedSequence",
      "org.bouncycastle.jce.provider.X509CertificateObject",
      "org.bouncycastle.jce.provider.PKCS12BagAttributeCarrierImpl",
      "org.bouncycastle.asn1.DERUTCTime",
      "org.bouncycastle.asn1.DERVisibleString",
      "org.jfree.data.general.DatasetChangeEvent",
      "org.apache.derby.jdbc.AutoloadedDriver",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.postgresql.core.Logger",
      "org.postgresql.Driver",
      "org.apache.derby.jdbc.InternalDriver",
      "org.hsqldb.DatabaseURL",
      "org.hsqldb.persist.HsqlProperties",
      "org.hsqldb.store.BaseHashMap",
      "org.hsqldb.store.ValuePoolHashMap",
      "org.hsqldb.store.HashIndex",
      "org.hsqldb.store.ValuePool",
      "org.postgresql.Driver$1",
      "org.jfree.data.time.RegularTimePeriod",
      "org.bouncycastle.asn1.DERGeneralizedTime",
      "org.testng.xml.XmlClass",
      "org.bouncycastle.asn1.DERIA5String",
      "com.caucho.inject.NamedLiteral",
      "net.sf.jsqlparser.parser.CCJSqlParser",
      "net.sf.jsqlparser.parser.CCJSqlParser$LookaheadSuccess",
      "net.sf.jsqlparser.parser.SimpleCharStream",
      "net.sf.jsqlparser.parser.CCJSqlParserTokenManager",
      "net.sf.jsqlparser.parser.Token",
      "net.sf.jsqlparser.parser.CCJSqlParser$JJCalls",
      "net.sf.jsqlparser.parser.ParseException",
      "net.sf.jsqlparser.parser.CCJSqlParserConstants",
      "net.sf.jsqlparser.JSQLParserException",
      "org.testng.junit.JUnitTestClass",
      "org.testng.junit.JUnit3TestClass",
      "org.testng.internal.BaseTestMethod$1",
      "org.testng.internal.BaseTestMethod",
      "org.testng.junit.JUnitTestMethod",
      "org.testng.junit.JUnit3TestMethod",
      "org.testng.internal.Utils$1",
      "org.testng.internal.Utils",
      "org.testng.TestRunner",
      "org.testng.internal.ConstructorOrMethod",
      "org.testng.internal.thread.ThreadUtil",
      "org.testng.internal.thread.AtomicIntegerAdapter",
      "com.caucho.config.Names",
      "org.bouncycastle.asn1.DEREnumerated",
      "org.bouncycastle.asn1.DERApplicationSpecific",
      "org.bouncycastle.asn1.BERApplicationSpecific",
      "org.bouncycastle.asn1.DERT61String",
      "org.bouncycastle.asn1.DEROutputStream",
      "org.bouncycastle.asn1.ASN1OutputStream",
      "org.bouncycastle.asn1.OIDTokenizer",
      "org.bouncycastle.asn1.DERExternal",
      "org.bouncycastle.asn1.DERPrintableString",
      "org.bouncycastle.asn1.ASN1Set",
      "org.bouncycastle.asn1.DERConstructedSet",
      "org.bouncycastle.math.ec.ECConstants",
      "org.jfree.data.category.DefaultIntervalCategoryDataset",
      "org.jfree.data.general.WaferMapDataset",
      "org.jfree.data.xy.DefaultXYDataset",
      "org.jfree.data.general.SubSeriesDataset",
      "org.bouncycastle.asn1.ASN1InputStream",
      "org.testng.junit.JUnit4TestClass",
      "org.testng.junit.JUnitUtils$JUnitTestClass",
      "org.testng.junit.JUnitUtils$JUnitTestMethod",
      "com.liferay.portal.kernel.util.ReflectionUtil",
      "com.liferay.portal.kernel.util.ProxyUtil",
      "com.liferay.portal.kernel.memory.EqualityWeakReference",
      "com.liferay.portal.security.pacl.PACLClassLoaderUtil",
      "com.liferay.portal.kernel.util.CentralizedThreadLocal$ThreadLocalMapThreadLocal",
      "com.liferay.portal.kernel.util.CentralizedThreadLocal",
      "com.liferay.portal.kernel.util.InitialThreadLocal",
      "com.liferay.portal.kernel.util.AutoResetThreadLocal",
      "com.liferay.portal.security.lang.PortalSecurityManagerThreadLocal",
      "com.liferay.portal.kernel.util.CentralizedThreadLocal$ThreadLocalMap",
      "com.liferay.portal.kernel.util.CentralizedThreadLocal$Entry",
      "com.liferay.portal.security.pacl.PACLPolicyManager",
      "org.bouncycastle.asn1.DERBMPString",
      "org.bouncycastle.asn1.DERSet",
      "org.bouncycastle.asn1.BERSet",
      "org.bouncycastle.asn1.ASN1Sequence$1",
      "org.bouncycastle.asn1.BERConstructedOctetString",
      "org.bouncycastle.asn1.DERInteger"
    );
  }
}
