/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 12 11:36:09 GMT 2024
 */

package fi.vtt.noen.testgen.observations.formatter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import fi.vtt.noen.testgen.observations.data.ArrayAttribute;
import fi.vtt.noen.testgen.observations.data.Event;
import fi.vtt.noen.testgen.observations.data.ProgramRun;
import fi.vtt.noen.testgen.observations.formatter.NoenFormatter;
import java.io.FileNotFoundException;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NoenFormatter_ESTest extends NoenFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter(".");
      String string0 = noenFormatter0.fileNameExtension();
      assertEquals("xml", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FileSystemHandling.shouldAllThrowIOExceptions();
      NoenFormatter noenFormatter0 = new NoenFormatter("\b/7TalrF6X:XM'");
      ProgramRun programRun0 = new ProgramRun("\b/7TalrF6X:XM'");
      // Undeclared exception!
      try { 
        noenFormatter0.observations(programRun0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Error while writing to file named '\b/7TalrF6X:XM''):Simulated IOException
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("5IgO|");
      ProgramRun programRun0 = new ProgramRun("5IgO|");
      programRun0.add((Event) null);
      // Undeclared exception!
      try { 
        noenFormatter0.observations(programRun0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.NoenFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("[");
      ProgramRun programRun0 = new ProgramRun("[");
      Event event0 = new Event("[");
      LinkedList<ArrayAttribute> linkedList0 = new LinkedList<ArrayAttribute>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      ArrayAttribute arrayAttribute0 = new ArrayAttribute("[", linkedList1);
      linkedList0.add(arrayAttribute0);
      event0.addAttribute("[", (Collection) linkedList0);
      programRun0.add(event0);
      // Undeclared exception!
      try { 
        noenFormatter0.observations(programRun0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class fi.vtt.noen.testgen.observations.data.ArrayAttribute cannot be cast to class java.lang.String (fi.vtt.noen.testgen.observations.data.ArrayAttribute is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @400f4c70; java.lang.String is in module java.base of loader 'bootstrap')
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.NoenFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      NoenFormatter noenFormatter0 = new NoenFormatter(pipedOutputStream0);
      // Undeclared exception!
      try { 
        noenFormatter0.header();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Error while writing to file named 'UNKNOWN-USING GIVEN STREAM'):Pipe not connected
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter((OutputStream) null);
      // Undeclared exception!
      try { 
        noenFormatter0.header();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      NoenFormatter noenFormatter0 = new NoenFormatter(pipedOutputStream0);
      // Undeclared exception!
      try { 
        noenFormatter0.footer();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Error while writing to file named 'UNKNOWN-USING GIVEN STREAM'):Pipe not connected
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("u;F:J0s-y}g.xml");
      FileSystemHandling.createFolder(evoSuiteFile0);
      NoenFormatter noenFormatter0 = null;
      try {
        noenFormatter0 = new NoenFormatter("u;F:J0s-y}g");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("double");
      ProgramRun programRun0 = new ProgramRun("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer@0000000002");
      Event event0 = new Event("nK.!_G~!E{{D", false);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.addFirst("double");
      event0.addAttribute("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer@0000000002", (Collection) linkedList0);
      programRun0.add(event0);
      noenFormatter0.observations(programRun0);
      assertEquals(1, noenFormatter0.getSCENARIOIDKEYINJECTED());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("double");
      ProgramRun programRun0 = new ProgramRun("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer@0000000002");
      Event event0 = new Event("nK.!_G~!E{{D", false);
      Iterator<Event> iterator0 = programRun0.iterator();
      event0.addAttribute("", (Object) iterator0);
      programRun0.add(event0);
      noenFormatter0.observations(programRun0);
      assertEquals(1, noenFormatter0.getSCENARIOIDKEYINJECTED());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("double");
      ProgramRun programRun0 = new ProgramRun("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer@0000000002");
      Event event0 = new Event("nK.!_G~!E{{D", false);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      event0.addAttribute("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer@0000000002", (Collection) linkedList0);
      programRun0.add(event0);
      noenFormatter0.observations(programRun0);
      assertEquals(1, noenFormatter0.getSCENARIOIDKEYINJECTED());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("/fJ9S*z<]");
      ProgramRun programRun0 = new ProgramRun("/fJ9S*z<]");
      Event event0 = new Event("/fJ9S*z<]", true);
      programRun0.add(event0);
      noenFormatter0.observations(programRun0);
      assertEquals(1, noenFormatter0.getSCENARIOIDKEYINJECTED());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter((OutputStream) null);
      // Undeclared exception!
      try { 
        noenFormatter0.footer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fi.vtt.noen.testgen.observations.formatter.BasicFormatter$OutputBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("double");
      noenFormatter0.footer();
      assertEquals("xml", noenFormatter0.fileNameExtension());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      NoenFormatter noenFormatter0 = new NoenFormatter("0");
      noenFormatter0.header();
      assertEquals("xml", noenFormatter0.fileNameExtension());
  }
}
