/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 10 00:31:51 GMT 2024
 */

package com.soops.CEN4010.JMCA.JParser;

import org.junit.Test;
import static org.junit.Assert.*;
import com.soops.CEN4010.JMCA.JParser.JavaParser;
import com.soops.CEN4010.JMCA.JParser.TestJava;
import java.io.PipedInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TestJava_ESTest extends TestJava_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestJava testJava0 = new TestJava();
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      JavaParser javaParser0 = new JavaParser(pipedInputStream0);
      testJava0.method1(9, 9, javaParser0);
      testJava0.method2();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestJava testJava0 = new TestJava();
      testJava0.method2();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestJava testJava0 = new TestJava();
      testJava0.method1((-272), (-1158.23811560581), (JavaParser) null);
      testJava0.method2();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TestJava testJava0 = new TestJava();
      testJava0.method1(2, 2, (JavaParser) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TestJava testJava0 = new TestJava();
      testJava0.method1(1, 1, (JavaParser) null);
  }
}
