/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 12 11:07:50 GMT 2024
 */

package de.huxhorn.lilith.consumers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer;
import de.huxhorn.lilith.data.eventsource.EventWrapper;
import de.huxhorn.lilith.data.eventsource.SourceIdentifier;
import de.huxhorn.lilith.data.logging.LoggingEvent;
import de.huxhorn.sulky.sounds.Sounds;
import de.huxhorn.sulky.sounds.jlayer.JLayerSounds;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AlarmSoundLoggingEventConsumer_ESTest extends AlarmSoundLoggingEventConsumer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      jLayerSounds0.setMute(true);
      Sounds sounds0 = alarmSoundLoggingEventConsumer0.getSounds();
      assertSame(sounds0, jLayerSounds0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      Sounds sounds0 = alarmSoundLoggingEventConsumer0.getSounds();
      assertSame(sounds0, jLayerSounds0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      // Undeclared exception!
      try { 
        alarmSoundLoggingEventConsumer0.consume((List<EventWrapper<LoggingEvent>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      EventWrapper<LoggingEvent> eventWrapper0 = new EventWrapper<LoggingEvent>();
      SourceIdentifier sourceIdentifier0 = new SourceIdentifier("\u0001uRK%- \u0000.[", "\u0001uRK%- \u0000.[");
      LoggingEvent loggingEvent0 = new LoggingEvent();
      LoggingEvent.Level loggingEvent_Level0 = LoggingEvent.Level.ERROR;
      loggingEvent0.setLevel(loggingEvent_Level0);
      EventWrapper<LoggingEvent> eventWrapper1 = new EventWrapper<LoggingEvent>(sourceIdentifier0, (-2231L), loggingEvent0);
      List<EventWrapper<LoggingEvent>> list0 = List.of(eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper1, eventWrapper1, eventWrapper1, eventWrapper0);
      alarmSoundLoggingEventConsumer0.consume(list0);
      assertTrue(list0.contains(eventWrapper1));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      JLayerSounds jLayerSounds0 = new JLayerSounds();
      alarmSoundLoggingEventConsumer0.setSounds(jLayerSounds0);
      EventWrapper<LoggingEvent> eventWrapper0 = new EventWrapper<LoggingEvent>();
      SourceIdentifier sourceIdentifier0 = new SourceIdentifier("\u0001uRK%- \u0000.[", "\u0001uRK%- \u0000.[");
      LoggingEvent loggingEvent0 = new LoggingEvent();
      EventWrapper<LoggingEvent> eventWrapper1 = new EventWrapper<LoggingEvent>(sourceIdentifier0, (-2231L), loggingEvent0);
      List<EventWrapper<LoggingEvent>> list0 = List.of(eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper0, eventWrapper1, eventWrapper1, eventWrapper1, eventWrapper0);
      alarmSoundLoggingEventConsumer0.consume(list0);
      assertEquals(9, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      LinkedList<EventWrapper<LoggingEvent>> linkedList0 = new LinkedList<EventWrapper<LoggingEvent>>();
      alarmSoundLoggingEventConsumer0.consume(linkedList0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AlarmSoundLoggingEventConsumer alarmSoundLoggingEventConsumer0 = new AlarmSoundLoggingEventConsumer();
      Sounds sounds0 = alarmSoundLoggingEventConsumer0.getSounds();
      assertNull(sounds0);
  }
}
