/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 12 03:56:55 GMT 2024
 */

package weka.core;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import weka.core.Version;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Version_ESTest extends Version_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("7-a<>K5");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Version version0 = new Version();
      Version.VERSION = null;
      String string0 = version0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Version version0 = new Version();
      Version.VERSION = "";
      String string0 = version0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Version version0 = new Version();
      boolean boolean0 = version0.isNewer("weka/core/version.txt");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      Version.MAJOR = 3;
      Version.MAJOR = (-1073741822);
      boolean boolean0 = version0.isNewer(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      Version.MAJOR = 3;
      Version.MAJOR = (-1073741822);
      boolean boolean0 = version0.isOlder(object0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Version version0 = new Version();
      boolean boolean0 = version0.equals("3.7.7");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = 7;
      Version.REVISION = 2191;
      int int0 = version0.compareTo("3.7.7");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = 4;
      int int0 = version0.compareTo("3.7.7");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Version version0 = new Version();
      Version.MINOR = 46;
      int int0 = version0.compareTo("3.7.7");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Version version0 = new Version();
      Version.MINOR = 3;
      int int0 = version0.compareTo("3.7.7");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("3.7.7");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      int int0 = version0.compareTo(object0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("8034");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = 4;
      boolean boolean0 = version0.equals("3.7.7");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Version.MINOR = 7;
      Version.MINOR = 4;
      Version.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      boolean boolean0 = version0.isOlder(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Version.VERSION = "";
      Version.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Version version0 = new Version();
      String string0 = version0.toString();
      assertEquals("3.7.7", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Version version0 = new Version();
      String string0 = version0.getRevision();
      assertEquals("8034", string0);
  }
}
